name: Build and Publish

on:
  workflow_dispatch:
  schedule:
    # Runs daily at 03:10 UTC
    - cron: "10 3 * * *"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nu
        uses: hustcer/setup-nu@v3

      - name: Run build script with Nu
        run: nu make.nu
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
